name: Asset Version Management

on:
  push:
    branches: [main]
    paths: ['**/*.css', '**/*.js']

permissions:
  contents: write

concurrency:
  group: asset-versioning-${{ github.ref }}
  cancel-in-progress: false

env:
  CONFIG_FILE: config.php

jobs:
  bump-versions:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # Pinned to v5.0.0 
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # Pinned to v47.0.0
        with:
          files_yaml: |
            css:
              - '**/*.css'
            js:
              - '**/*.js'

      - name: Check if versions need bumping
        id: check
        run: |
          get_version() {
            local content=$1
            local type=$2
            echo "$content" | grep "const WEBSITE_${type}_VERSION = " | sed 's/.*= \([0-9]*\);.*/\1/' || echo "0"
          }
          
          current_config=$(cat $CONFIG_FILE)
          css_current=$(get_version "$current_config" "CSS")
          js_current=$(get_version "$current_config" "JS")
          
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [[ -n "$latest_tag" ]]; then
            release_config=$(git show ${latest_tag}:${CONFIG_FILE} 2>/dev/null || echo "")
            css_at_release=$(get_version "$release_config" "CSS")
            js_at_release=$(get_version "$release_config" "JS")
          else
            css_at_release=0
            js_at_release=0
          fi
          
          bump_css=false
          bump_js=false
          
          if [[ "${{ steps.changes.outputs.css_any_changed }}" == "true" && $css_current -le $css_at_release ]]; then
            bump_css=true
            echo "✓ CSS files changed and version needs bump (current: $css_current, last release: $css_at_release)"
          fi
          
          if [[ "${{ steps.changes.outputs.js_any_changed }}" == "true" && $js_current -le $js_at_release ]]; then
            bump_js=true
            echo "✓ JS files changed and version needs bump (current: $js_current, last release: $js_at_release)"
          fi
          
          echo "bump_css=$bump_css" >> $GITHUB_OUTPUT
          echo "bump_js=$bump_js" >> $GITHUB_OUTPUT
          echo "css_current=$css_current" >> $GITHUB_OUTPUT
          echo "js_current=$js_current" >> $GITHUB_OUTPUT

      - name: Bump versions
        if: steps.check.outputs.bump_css == 'true' || steps.check.outputs.bump_js == 'true'
        run: |
          if [[ "${{ steps.check.outputs.bump_css }}" == "true" ]]; then
            current=${{ steps.check.outputs.css_current }}
            new=$((current + 1))
            sed -i "s/const WEBSITE_CSS_VERSION = $current;/const WEBSITE_CSS_VERSION = $new;/" $CONFIG_FILE
            echo "CSS: $current → $new"
          fi
          
          if [[ "${{ steps.check.outputs.bump_js }}" == "true" ]]; then
            current=${{ steps.check.outputs.js_current }}
            new=$((current + 1))
            sed -i "s/const WEBSITE_JS_VERSION = $current;/const WEBSITE_JS_VERSION = $new;/" $CONFIG_FILE
            echo "JS: $current → $new"
          fi

      - name: Commit changes
        if: steps.check.outputs.bump_css == 'true' || steps.check.outputs.bump_js == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "Auto-bump asset versions [skip ci]"
          file_pattern: ${{ env.CONFIG_FILE }}