name: Asset Version Management

on:
  push:
    branches: [main]
    paths: ['**/*.css', '**/*.js']

permissions:
  contents: write

jobs:
  bump-versions:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            css:
              - '**/*.css'
            js:
              - '**/*.js'

      - name: Check if versions need bumping
        id: check
        run: |
          # Get latest release tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          # Check if already bumped since release
          css_bumped=false
          js_bumped=false
          
          if [[ -n "$latest_tag" ]]; then
            # Get commit hashes (not full log lines) for auto-bump commits
            auto_bump_commits=$(git log ${latest_tag}..HEAD --format="%H" --grep="Auto-bump asset versions")
            
            if [[ -n "$auto_bump_commits" ]]; then
              for commit in $auto_bump_commits; do
                if git show "$commit" -- config.php | grep -q "^+.*WEBSITE_CSS_VERSION"; then
                  css_bumped=true
                fi
                if git show "$commit" -- config.php | grep -q "^+.*WEBSITE_JS_VERSION"; then
                  js_bumped=true
                fi
              done
            fi
          fi
          
          # Determine what to bump
          bump_css=false
          bump_js=false
          
          if [[ "${{ steps.changes.outputs.css_any_changed }}" == "true" && "$css_bumped" == "false" ]]; then
            bump_css=true
            echo "✅ Will bump CSS version"
          fi
          
          if [[ "${{ steps.changes.outputs.js_any_changed }}" == "true" && "$js_bumped" == "false" ]]; then
            bump_js=true
            echo "✅ Will bump JS version"
          fi
          
          echo "bump_css=$bump_css" >> $GITHUB_OUTPUT
          echo "bump_js=$bump_js" >> $GITHUB_OUTPUT

      - name: Bump versions
        if: steps.check.outputs.bump_css == 'true' || steps.check.outputs.bump_js == 'true'
        run: |
          if [[ "${{ steps.check.outputs.bump_css }}" == "true" ]]; then
            current=$(grep "WEBSITE_CSS_VERSION = " config.php | sed 's/.*= \([0-9]*\);.*/\1/')
            new=$((current + 1))
            sed -i "s/WEBSITE_CSS_VERSION = $current;/WEBSITE_CSS_VERSION = $new;/" config.php
            echo "🎨 CSS version: $current → $new"
          fi
          
          if [[ "${{ steps.check.outputs.bump_js }}" == "true" ]]; then
            current=$(grep "WEBSITE_JS_VERSION = " config.php | sed 's/.*= \([0-9]*\);.*/\1/')
            new=$((current + 1))
            sed -i "s/WEBSITE_JS_VERSION = $current;/WEBSITE_JS_VERSION = $new;/" config.php
            echo "⚡ JS version: $current → $new"
          fi

      - name: Commit changes
        if: steps.check.outputs.bump_css == 'true' || steps.check.outputs.bump_js == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-bump asset versions [skip ci]"
          file_pattern: config.php