name: Asset Version Management

on:
  push:
    branches: [main]
    paths: ['**/*.css', '**/*.js']

permissions:
  contents: write

concurrency:
  group: asset-versioning-${{ github.ref }}
  cancel-in-progress: false

jobs:
  bump-versions:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@47.0.0
        with:
          files_yaml: |
            css:
              - '**/*.css'
            js:
              - '**/*.js'

      - name: Check if versions need bumping
        id: check
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          css_bumped=false
          js_bumped=false
          
          if [[ -n "$latest_tag" ]]; then
            css_version_at_release=$(git show ${latest_tag}:config.php | grep "WEBSITE_CSS_VERSION = " | sed 's/.*= \([0-9]*\);.*/\1/' || echo "0")
            js_version_at_release=$(git show ${latest_tag}:config.php | grep "WEBSITE_JS_VERSION = " | sed 's/.*= \([0-9]*\);.*/\1/' || echo "0")
            
            css_version_current=$(grep "WEBSITE_CSS_VERSION = " config.php | sed 's/.*= \([0-9]*\);.*/\1/')
            js_version_current=$(grep "WEBSITE_JS_VERSION = " config.php | sed 's/.*= \([0-9]*\);.*/\1/')
            
            if [[ $css_version_current -gt $css_version_at_release ]]; then
              css_bumped=true
            fi
            
            if [[ $js_version_current -gt $js_version_at_release ]]; then
              js_bumped=true
            fi
          fi
          
          bump_css=false
          bump_js=false
          
          if [[ "${{ steps.changes.outputs.css_any_changed }}" == "true" && "$css_bumped" == "false" ]]; then
            bump_css=true
          fi
          
          if [[ "${{ steps.changes.outputs.js_any_changed }}" == "true" && "$js_bumped" == "false" ]]; then
            bump_js=true
          fi
          
          echo "bump_css=$bump_css" >> $GITHUB_OUTPUT
          echo "bump_js=$bump_js" >> $GITHUB_OUTPUT

      - name: Bump versions
        if: steps.check.outputs.bump_css == 'true' || steps.check.outputs.bump_js == 'true'
        run: |
          set -euo pipefail
          
          if [[ "${{ steps.check.outputs.bump_css }}" == "true" ]]; then
            current=$(grep "WEBSITE_CSS_VERSION = " config.php | sed 's/.*= \([0-9]*\);.*/\1/')
            if [[ ! "$current" =~ ^[0-9]+$ ]]; then
              echo "❌ Invalid CSS version format: $current"
              exit 1
            fi
            new=$((current + 1))
            sed -i "s/const WEBSITE_CSS_VERSION = $current;/const WEBSITE_CSS_VERSION = $new;/" config.php
            echo "CSS: $current → $new"
          fi
          
          if [[ "${{ steps.check.outputs.bump_js }}" == "true" ]]; then
            current=$(grep "WEBSITE_JS_VERSION = " config.php | sed 's/.*= \([0-9]*\);.*/\1/')
            if [[ ! "$current" =~ ^[0-9]+$ ]]; then
              echo "❌ Invalid JS version format: $current"
              exit 1
            fi
            new=$((current + 1))
            sed -i "s/const WEBSITE_JS_VERSION = $current;/const WEBSITE_JS_VERSION = $new;/" config.php
            echo "JS: $current → $new"
          fi

      - name: Commit changes
        if: steps.check.outputs.bump_css == 'true' || steps.check.outputs.bump_js == 'true'
        uses: stefanzweifel/git-auto-commit-action@6.0.1
        with:
          commit_message: "Auto-bump asset versions [skip ci]"
          file_pattern: config.php