name: Rollbar Deploy Notification

on:
  release:
    types: [published]

permissions:
  contents: read
  actions: read

jobs:
  notify-rollbar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Get current website version
        id: get-version
        run: |
          # Extract current version from config.php
          current_version=$(grep "WEBSITE_VERSION = '" config.php | sed "s/.*WEBSITE_VERSION = '\([^']*\)'.*/\1/")
          echo "Website version: $current_version"
          echo "version=$current_version" >> $GITHUB_OUTPUT

      - name: Notify Rollbar of deployment
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        run: |
          echo "Notifying Rollbar of deployment..."
          echo "Release: ${{ github.event.release.tag_name }}"
          echo "Website version: ${{ steps.get-version.outputs.version }}"
          
          response=$(curl -X POST 'https://api.rollbar.com/api/1/deploy/' \
            -H 'Content-Type: application/json' \
            -H "X-Rollbar-Access-Token: $ROLLBAR_ACCESS_TOKEN" \
            -d '{
              "environment": "production",
              "revision": "${{ steps.get-version.outputs.version }}",
              "rollbar_name": "GitHub Actions",
              "local_username": "github-actions",
              "comment": "Production deployment - Release: ${{ github.event.release.tag_name }}"
            }')
          
          echo "Rollbar API response: $response"
          echo "✅ Rollbar notified successfully"